os:
  - linux
  - windows
  - osx

language: node_js
node_js:
- 14

script:
  - npm run c
  - npm run doc
  - npm run test

after_success:
  - npm run coverage
  - npm run coveralls

branches:
  only:
  - main
